name = "hbdr-website"
main = "worker.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
tsconfig = "tsconfig.worker.json"

[assets]
directory = "./public"

[vars]
ENVIRONMENT = "production"
ADMIN_PASSWORD = "hbdr2025!"
SITE_URL = "https://hbdr.com"

[[d1_databases]]
binding = "DB"
database_name = "hbdr-website-database"
database_id = "141aed40-1a51-46ac-a795-31e1c913a626"
